server:
  port: 8082
  forward-headers-strategy: framework

spring:
  application:
    name: demo-email
  mail:
    host: smtp.gmail.com
    port: 587
#    port: 465
    username: ${GOOGLE_APP_EMAIL}
    password: ${GOOGLE_APP_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
# Se debe habilitar si se usa el puerto {spring.mail.port:465}
#          ssl:
#            enable: true
# Se debe habilitar si se usa el puerto {spring.mail.port:587}
          starttls:
            enable: true

# Variables de entorno
gateway:
  secret: ${X-GATEWAY-SECRET:crearVariableEntorno}
